title: Page

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            label: Text
            type: textarea
            size: large
  sidebar:
    width: 1/3
    sections:
      files:
        type: files
        headline: Files
      sidebar:
        type: fields
        fields:
          date:
            label: Date
            type: date
            default: today
          time:
            label: Time
            type: time
            default: now
            notation: 12


